services:
    oss.core.repository.team:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [OSS\CoreBundle\Entity\Team]

    oss.core.repository.transfer_offer:
        class: OSS\CoreBundle\Repository\TransferOfferRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [OSS\CoreBundle\Entity\TransferOffer]
