services:
    twig.extension.game_date:
        class: OSS\CoreBundle\Twig\GameDateExtension
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: twig.extension }

    twig.extension.number:
        class: OSS\CoreBundle\Twig\NumberExtension
        tags:
            - { name: twig.extension }

    oss.core.service.fixture:
        class: OSS\CoreBundle\Services\FixtureService
        arguments: [@doctrine.orm.entity_manager]

    oss.core.service.league:
        class: OSS\CoreBundle\Services\LeagueService
        arguments: [@doctrine.orm.entity_manager]

    oss.core.service.match_evaluation:
        class: OSS\CoreBundle\Services\MatchEvaluationService

    oss.core.service.transfer:
        class: OSS\CoreBundle\Services\TransferService
        arguments: [@doctrine.orm.entity_manager]
