services:
    twig.extension.game_date:
        class: OSS\CoreBundle\Twig\GameDateExtension
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: twig.extension }

    oss.core.service.transfer:
        class: OSS\CoreBundle\Services\TransferService
        arguments: [@doctrine.orm.entity_manager]
